#!/usr/bin/env python3
"""Run the compiler on the running example and write the diagnostics the paper quotes.

The manuscript includes examples/triage.orch verbatim (lstinputlisting) and the first
diagnostic of `orchc check` from sections/triage-output.tex, so neither can drift from
what the compiler actually does.  Run from submission/scp: python3 examples/run.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ORCHC = os.path.join(HERE, '..', '..', '..', 'orchc')
EXPECTED = {'triage.orch': ('E236', 1), 'triage_unendorsed.orch': ('E233', 1),
            'triage_leaks.orch': ('W238', 0)}


def run(name):
    completed = subprocess.run([ORCHC, 'check', name], cwd=HERE, capture_output=True, text=True)
    return completed.returncode, (completed.stderr + completed.stdout).strip().splitlines()


def escape(text):
    for a, b in (('\\', '\\textbackslash{}'), ('_', '\\_'), ('{', '\\{'), ('}', '\\}'),
                 ('#', '\\#'), ('%', '\\%'), ('&', '\\&'), ('$', '\\$')):
        text = text.replace(a, b)
    return text


failed = False
for name, (code, status) in EXPECTED.items():
    returncode, lines = run(name)
    if returncode != status or code not in lines[0]:
        print('%s: expected %s with exit %d, got exit %d: %s' % (name, code, status, returncode, lines[0]))
        failed = True
returncode, lines = run('triage.orch')
with open(os.path.join(HERE, '..', 'sections', 'triage-output.tex'), 'w', encoding='utf-8') as handle:
    handle.write('%% Generated by examples/run.py from `orchc check triage.orch`. Do not edit.\n')
    handle.write(escape(lines[0]) + '\n')
print('ok' if not failed else 'FAILED')
sys.exit(1 if failed else 0)
