#pragma once

// What the compiler may assume about a real tokenizer.
//
// A guaranteed input-token bound needs a sound way to turn a length in bytes
// into a count of tokens.  Nothing in a tokenizer's documentation supplies one,
// and several plausible assumptions are false (bench/results/tokenizers.txt):
// token counts do not add up under concatenation, a response re-encodes to more
// tokens than the model generated, SentencePiece tokenizers add a token that no
// byte pays for, and NFKC-normalising tokenizers can emit more tokens than the
// text has bytes.
//
// So each entry below states a contract of the form
//
//     tokens(s)  <=  kappa * bytes(s)  +  sigma
//
// and says why it holds.  Where the argument is structural (every token covers
// at least one byte of the text it came from) the entry is marked verified and
// the exhaustive measurement is a check on the argument, not the argument
// itself.  Where no structural argument exists the entry is unverified, and the
// compiler refuses to derive a guaranteed bound through it.
//
// lambda bounds the other direction, which a chained call needs: how many bytes
// one generated token can decode to, after a provider replaces ill-formed UTF-8.
//
// The numeric fields are generated by bench/tokenizers/contracts.py from
// bench/results/tokenizers.json.  Do not edit them by hand.

#include <cstddef>
#include <string>

namespace orchlang {

struct TokenizerContract {
    const char* name;
    const char* family;
    // True when tokens(s) <= kappa * bytes(s) + sigma holds for every string,
    // by an argument from the tokenizer's structure.
    bool verified;
    std::size_t kappa;
    // Tokens the tokenizer adds that no byte of the text pays for: a
    // SentencePiece dummy prefix, and special tokens added to every request.
    std::size_t sigma;
    // Most bytes one vocabulary entry decodes to, after lossy UTF-8 decoding.
    std::size_t lambda;
    // True when encoding applies no normalisation that can shrink the text, so
    // a string that encodes to N tokens has at most lambda * N bytes.  False
    // for NFC and NFKC normalisers, which compose several code points into one.
    bool lossless;
    const char* evidence;
};

// Null if the name is not a known tokenizer.
const TokenizerContract* findTokenizerContract(const std::string& name);

// The names, for diagnostics.
std::string knownTokenizerNames();

}  // namespace orchlang
