// GENERATED by bench/tokenizers/contracts.py from bench/results/tokenizers.json.
// Do not edit by hand: rerun the measurement and the generator instead.
//
// Measured on 14 real tokenizers, Unicode 14.0.0, 388 UDHR languages.

#include "tokenizer_contracts.hpp"

#include <sstream>

namespace orchlang {

namespace {

const TokenizerContract kContracts[] = {
    {"cl100k_base", "byte-level BPE", true, 1, 0, 128, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"o200k_base", "byte-level BPE", true, 1, 0, 128, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"r50k_base", "byte-level BPE", true, 1, 0, 128, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"llama3", "byte-level BPE", true, 1, 1, 128, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"qwen25", "byte-level BPE after NFC", true, 3, 0, 128, false,
     "tokens <= bytes(NFC(s)) <= 3 bytes(s); NFD expands a code point at most 3x (UAX #15), composition never lengthens; measured max per code point 3 tokens over bytes"},
    {"deepseekv3", "byte-level BPE", true, 1, 0, 128, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"olmo2", "byte-level BPE", true, 1, 0, 128, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"gpt2", "byte-level BPE", true, 1, 0, 128, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"llama2", "SentencePiece BPE, byte fallback", true, 1, 2, 27, true,
     "every token covers at least one byte (plus one dummy-prefix piece); exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 1"},
    {"mistral", "SentencePiece BPE, byte fallback", true, 1, 2, 25, true,
     "every token covers at least one byte (plus one dummy-prefix piece); exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 1"},
    {"phi3", "SentencePiece BPE, byte fallback", true, 1, 1, 27, true,
     "every token covers at least one byte (plus one dummy-prefix piece); exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 1"},
    {"gemma2", "SentencePiece BPE, byte fallback", true, 1, 1, 48, true,
     "every token covers at least one byte; exhaustive over 1112064 scalar values and 495 strings, max tokens-bytes 0"},
    {"t5", "SentencePiece Unigram, no byte fallback, NFKC-like charsmap", false, 0, 0, 18, false,
     "no structural bound; measured +194 tokens over bytes on one string"},
    {"xlmr", "SentencePiece Unigram, no byte fallback, NFKC-like charsmap", false, 0, 0, 48, false,
     "no structural bound; measured +64 tokens over bytes on one string"},
    {"mockbpe", "OrchLang runtime mock (greedy longest match, byte fallback)", true, 1, 0, 12, true,
     "by construction: every token covers at least one byte; a mock output unit is at most 12 bytes"},
};

}  // namespace

const TokenizerContract* findTokenizerContract(const std::string& name) {
    for (const TokenizerContract& contract : kContracts) {
        if (name == contract.name) {
            return &contract;
        }
    }
    return nullptr;
}

std::string knownTokenizerNames() {
    std::ostringstream out;
    bool first = true;
    for (const TokenizerContract& contract : kContracts) {
        out << (first ? "" : ", ") << contract.name;
        first = false;
    }
    return out.str();
}

}  // namespace orchlang
